This is makeindex, version 2.15 [TeX Live 2020] (kpathsea + Thai support).
Scanning style file ./report.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file report.acn....done (204 entries accepted, 0 rejected).
Sorting entries.....done (1693 comparisons).
Generating output file report.acr....done (149 lines written, 0 warnings).
Output written in report.acr.
Transcript written in report.alg.
